from enum import Enum


class GEO_DICT(Enum):

    NODES = "NODES"

    ELEMENTS = "ELEMENTS"
    CELLS = "ELEMENTS"

    NODESETS = "NODESETS"

    ELEMTSETS = "ELEMTSETS"

    SURFACES = "SURFACES"

    VIRTUAL_NODES = "VIRTUAL_NODES"

    DISCRETE_SETS = "DISCRETE_SETS"

    BC = "BOUNDARY_CONDITIONS"

    MESH_POINT_DATA = "MESH_NODE_DATA"
    MESH_CELL_DATA = "MESH_ELEM_DATA"
    
    STATES = "STATES"
