name: Build Docs with Sphinx
on: [push, pull_request]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install pandoc
        run: |
          sudo apt-get install --no-install-recommends pandoc
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Double-check Python version
        run: |
          python3 --version
      - name: Install Python package
        run: |
          python3 -m pip install .
      - name: Install docs dependencies
        run: |
          python3 -m pip install -r docs/requirements.txt
      - name: Build HTML
        run: |
          python3 -m sphinx -W --keep-going --color doc/ _build/html/ -d _build/doctrees/ -b html
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: html-docs
          path: docs/build/html/
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html